name: CI

on:
  push:
    branches: [ main ]  # Run CI on push to main branch
  pull_request:
    branches: [ main ]  # Run CI on pull requests targeting main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1  # Specify the correct action version

    - name: Build and test
      run: |
        dotnet restore
        dotnet build --configuration Release
